### PR TITLE
Rahul Arora Submission

### PR DESCRIPTION
**Pull request by rarora7777**

### CODE REVIEW

**Comment by alecjacobson** [comment]
Were these changes to glfw something that you needed to make to get the example to run (and I should merge them to my master copy) or something auto-generated by cmake?

**Comment by rarora7777** [comment]
These were auto-generated. Should I send you a merge request with these changes removed?

**Comment by alecjacobson** [comment]
Nah it's fine.

**Comment by alecjacobson** [comment]
In the future, I will try to put `build/` in the .gitignore to begin with. But just in case, please do not commit `build/` as part of the PR (it's big and slows down grading a bit).

**Comment by alecjacobson** [comment]
✔️

**Pull request closed without merging**
